CREATE TABLE authority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(6)
);

CREATE TABLE "users" (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR(255) DEFAULT NULL,
     password VARCHAR(255) DEFAULT NULL,
     user_name VARCHAR(255) DEFAULT NULL,
     uuid UUID NOT NULL,
     is_active BOOLEAN DEFAULT NULL,
     created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
     updated_at TIMESTAMP(6),
     CONSTRAINT UKob8kqyqqgmefl0aco34akdtpe UNIQUE (email),
     CONSTRAINT UKlqjrcobrh9jc8wpcar64q1bfh UNIQUE (user_name)
);

CREATE TABLE user_authorities (
      authority_id INT NOT NULL,
      user_id INT NOT NULL,
      PRIMARY KEY (authority_id, user_id),
      CONSTRAINT FKmj13d0mnuj4cd8b6htotbf9mm FOREIGN KEY (user_id) REFERENCES "users" (id),
      CONSTRAINT FK2n9bab2v62l3y2jgu3qup4etw FOREIGN KEY (authority_id) REFERENCES authority (id)
);