### POST request to create patient
POST http://localhost:4003/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "patient-appointment-test",
  "email": "patient-appointment-test1@gmail.com",
  "address": "123 Main Street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-10-27"
}

###