### POST request to create patient
POST http://localhost:4003/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "circuit-breaker-test3",
  "email": "circuit-breaker-test3@gmail.com",
  "address": "123 Main Street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-09-09" 
}

###