### Request to update patient
PUT http://localhost:8080/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "updated-patient",
  "email": "updated_email@gmail.com",
  "address": "123 Main Street",
  "dateOfBirth": "1995-09-09"
}

###