### Request to update patient
PUT http://localhost:4003/api/patients/c6a36342-180d-496f-b3e8-5beb5511f0a3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "updated-patient-for-appointment2",
  "email": "updatedPatient2@gmail.com",
  "address": "address from api",
  "dateOfBirth": "2025-10-27"
}

###