CREATE TABLE patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    date_of_birth DATE,
    registered_date DATE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(6)
);

-- index for email
CREATE UNIQUE INDEX idx_patient_email ON patient(email);

